jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    default_context:
        serialization:
            serialize_null: true

    metadata:
        directories:
            KnpPaginatorBundle:
                namespace_prefix: Knp\Bundle\PaginatorBundle
                path:             '%kernel.root_dir%/../config/jms/KnpPaginatorBundle'
            KnpPager:
                namespace_prefix: Knp\Component\Pager
                path:             '%kernel.root_dir%/../config/jms/KnpPager'
